### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by MrTinker64** [MrTinker64/Quake#1]
Remember to keep following SOLID and organized principles the whole time!
- [ ] Learn how to use in-line commands
- [ ]  Learn how to code swerve
- [ ] Learn how to unit test
- [ ] Learn how the simulation works
- [ ] Learn what state-space is
- [ ] Learn how to do trajectory setting
